### ISSUE TITLE
Pretrained Weights

### ISSUE THREAD

**Issue by HamadYA** [ubc-vision/LDM_correspondences#1]
Hi,

Thanks for the amazing work. Could you please provide the pretrained weights?

**Comment by ehedlin** [comment]
The only pretrained weights for this are from Stable Diffusion itself. The attention map is found per keypoint per image. The version of stable diffusion is set [here](https://github.com/ubc-vision/LDM_correspondences/blob/97e3246f0fcfd92eee6cf03e6cb085c24a7fc768/eval/eval.py#L62)
